name: Deploy Blog

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Caching  Node Modules
        id: node-cache-build
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}--toby-homepage-site-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-toby-homepage-site-build-
      - name: Install dependencies
        run: npm install
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
      - name: Build and Deploy
        run: yarn run deploy
